### ISSUE TITLE
[Epic] Migrate docs from current Sphinx/rst based format to mkdocs and Markdown

### ISSUE THREAD

**Issue by foosel** [OctoPrint/docs#2]
Sub tasks (still building up, in no way to be considered exhaustive yet):

- [ ] migrate features
  - [ ] access control
  - [ ] custom controls
  - [ ] gcode scripts
  - [ ] action commands
  - [ ] at commands
  - [ ] plugins
  - [x] safe mode
- [ ] bundled plugins
  - [ ] action command notification
  - [ ] action command prompt
  - [ ] announcement
  - [ ] anonymous usage tracking
  - [ ] application keys
  - [ ] backup
  - [ ] discovery
  - [ ] error tracking
  - [ ] file check
  - [ ] firmware check
  - [ ] gcode viewer
  - [ ] logging
  - [ ] plugin manager
  - [ ] software update
  - [ ] virtual printer
- [x] migrate config stuff
  - [x] yaml primer
  - [x] config.yaml
  - [x] logging.yaml
  - [x] cli
- [ ] migrate events
  - [ ] event list into dev section
  - [ ] config into features
- [ ] migrate REST API
  - [ ] Link basic REST primer
- [ ] migrate JS Client lib docs
- [ ] migrate core dev stuff
  - [ ] versioning
  - [ ] branching
  - [ ] dev environment
  - [ ] virtual printer
  - [ ] profiling
- [ ] migrate Plugin dev guide
  - [x] general concepts
  - [x] control properties
  - [x] mixins
  - [ ] hooks
  - [x] helpers
  - [x] injected properties
  - [ ] viewmodels
  - [ ] tutorial
  - [ ] distribution
  - [ ] python 3 migration (?)

Migration of docstrings happens in ['improve/mkdocs' branch of OctoPrint/OctoPrint](https://github.com/OctoPrint/OctoPrint/tree/improve/mkdocs). Current preview available at [octoprint.github.io/docs](https://octoprint.github.io/docs).

Open questions:

- What to do about existing deep links into the Sphinx based documentation structure? Add a ton of redirects? Can this somehow be automated? If not, just go through the pain of some 404s?

**Comment by foosel** [comment]
Issues with mkdocstrings:

- Tricky to manually enable protected parts of the API (e.g. stuff that's supposed to be implemented in subclasses) to be rendered into the docs. An adjustment of `gen_ref_pages.py` however helps here (regexes with additional options for mkdocstrings), see [here](https://github.com/OctoPrint/docs/blob/56b1bc959fe4edcea305793e4df5c35c6e847e6e/extensions/gen_ref_pages.py#L21-L26) and [here](https://github.com/OctoPrint/docs/blob/56b1bc959fe4edcea305793e4df5c35c6e847e6e/extensions/gen_ref_pages.py#L52-L61).
- No option that I have so far found to manually add additional member functions to a class doc, as needed for `PluginSettings`. The getters and setters are implemented dynamically through `__getattr__`. It might work through a simple list, but that's ugly, doesn't integrate with the toc and is overall just meh.

So I got the idea to check out [Myst](https://myst-parser.readthedocs.io) and [sphinx-autodoc2](https://sphinx-autodoc2.readthedocs.io). And at first things look good, but alas, `sphinx-autodoc2` currently doesn't support our Google docstrings, e.g. 

```
Arguments
  foo (str): doc for foo

Returns:
  (str): Some return value
```

It only supports Sphinx based parameter docs, e.g.

```
:param str foo: doc for foo
:rtype str:
:return: Some return value
```

That's obviously less readable, and thus would be a step backwards. So for now we'd not be able to use Markdown in the docstrings, which would then get us back to having to write Restructured Text, and this whole exercise here is about getting rid of rSt for good.

I'm starting to feel the tooling might not yet be fully there. I'll tinker around with both a bit more to see if I can find solutions for either one that will work for OctoPrint.
